bindAddr = "0.0.0.0"
bindPort = 9527

#[auth]
#method = "token"
#token = "YOUR_TOKEN"

#[[auth.token_policies]]
#token = "YOUR_TOKEN"
#allowed_tunnels = ["mysql"]
#allowed_protocols = ["tcp"]
#allowed_remote_ports = [6050]

#[webServer]
#addr = "0.0.0.0"
#port = 8020
#user = "YOUR_USERNAME"      # Required when port > 0
#password = "YOUR_PASSWORD"  # Required when port > 0; use a strong password
