orbien:
  enabled: true
  server-addr: 127.0.0.1
  server-port: 9527
  token: YOUR_TOKEN
  tcp-mux: false
  pool-count: 1
  heartbeat-interval-secs: 30
  user: java-demo
  tunnel:
    name: java-demo-http
    protocol: http
    local-ip: 127.0.0.1
    domains:
      - web.example.com
      - admin
